///*
// * This Kotlin source file was generated by the Gradle 'init' task.
// */
//package jennifer.dojo.common
//
//import kotlin.test.Test
//import kotlin.test.assertTrue
//
//class LibraryTest {
//    @Test fun testSomeLibraryMethod() {
//        val classUnderTest = Library()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
//    }
//
//
//    @Test fun testInt(){
//        val list = mutableListOf<Int>(2)
//        println(list)
//    }
//
//
//}
